name: Kover Code Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  pull-requests: write

env:
  IS_GITHUB_CI: true

jobs:
  kover-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check file changes
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            src:
              - 'src/**'
              - 'gradle/**'
              - 'build.gradle.kts'
              - 'settings.gradle.kts'
              - 'gradle.properties'
              - '.github/workflows/kover.yml'

      - name: Set up JDK
        if: steps.filter.outputs.src == 'true'
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # Automatic gradle caching using `actions/cache@v4`
      # https://github.com/gradle/actions/tree/main/setup-gradle
      - name: Setup Gradle
        if: steps.filter.outputs.src == 'true'
        uses: gradle/actions/setup-gradle@v6

      # Generates reports in following location:
      # - build/reports/kover/html/index.html
      # - build/reports/kover/report.xml
      - name: Run Kover Coverage Reports
        if: steps.filter.outputs.src == 'true'
        run: ./gradlew koverHtmlReport koverXmlReport

      # https://github.com/actions/upload-artifact
      - name: Upload Kover report
        if: steps.filter.outputs.src == 'true'
        uses: actions/upload-artifact@v6
        with:
          name: kover-report
          path: build/reports/kover/html

      # Sticky Pull Request Comment
      # https://github.com/marocchino/sticky-pull-request-comment
      - name: Post coverage comment
        if: steps.filter.outputs.src == 'true' && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v3
        with:
          message: |
            ## Code Coverage Report
            [View Coverage Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

      # GitHub Action that uploads coverage to Codecov ☂️
      # https://github.com/codecov/codecov-action
      - name: Upload coverage reports to Codecov
        if: steps.filter.outputs.src == 'true'
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/kover/report.xml
          slug: ${{ github.repository }}
